/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DAOGovernanceOptimized {
  export type ProposalStruct = {
    votesFor: BigNumberish;
    votesAgainst: BigNumberish;
    deadline: BigNumberish;
    proposalId: BigNumberish;
    proposalType: BigNumberish;
    category: BigNumberish;
    executed: boolean;
    passed: boolean;
  };

  export type ProposalStructOutput = [
    votesFor: bigint,
    votesAgainst: bigint,
    deadline: bigint,
    proposalId: bigint,
    proposalType: bigint,
    category: bigint,
    executed: boolean,
    passed: boolean
  ] & {
    votesFor: bigint;
    votesAgainst: bigint;
    deadline: bigint;
    proposalId: bigint;
    proposalType: bigint;
    category: bigint;
    executed: boolean;
    passed: boolean;
  };
}

export interface DAOGovernanceOptimizedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "QUORUM"
      | "TIMELOCK"
      | "VOTING_PERIOD"
      | "execute"
      | "executionTime"
      | "getProposal"
      | "proposalCounter"
      | "proposalDetails"
      | "proposals"
      | "propose"
      | "token"
      | "voteQuadratic"
      | "votes"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProposalCreated"
      | "ProposalExecuted"
      | "VotedQuadratic"
  ): EventFragment;

  encodeFunctionData(functionFragment: "QUORUM", values?: undefined): string;
  encodeFunctionData(functionFragment: "TIMELOCK", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "VOTING_PERIOD",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "execute",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executionTime",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProposal",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposalCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proposalDetails",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "proposals",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "propose",
    values: [BigNumberish, BigNumberish, string, string]
  ): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "voteQuadratic",
    values: [BigNumberish, BigNumberish, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "votes",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "QUORUM", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "TIMELOCK", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "VOTING_PERIOD",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "execute", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executionTime",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProposal",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proposalDetails",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "proposals", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "propose", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "voteQuadratic",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "votes", data: BytesLike): Result;
}

export namespace ProposalCreatedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    proposalType: BigNumberish,
    category: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    proposalType: bigint,
    category: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    proposalType: bigint;
    category: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProposalExecutedEvent {
  export type InputTuple = [proposalId: BigNumberish, passed: boolean];
  export type OutputTuple = [proposalId: bigint, passed: boolean];
  export interface OutputObject {
    proposalId: bigint;
    passed: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VotedQuadraticEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    voter: AddressLike,
    voteAmount: BigNumberish,
    tokensCost: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    voter: string,
    voteAmount: bigint,
    tokensCost: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    voter: string;
    voteAmount: bigint;
    tokensCost: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DAOGovernanceOptimized extends BaseContract {
  connect(runner?: ContractRunner | null): DAOGovernanceOptimized;
  waitForDeployment(): Promise<this>;

  interface: DAOGovernanceOptimizedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  QUORUM: TypedContractMethod<[], [bigint], "view">;

  TIMELOCK: TypedContractMethod<[], [bigint], "view">;

  VOTING_PERIOD: TypedContractMethod<[], [bigint], "view">;

  execute: TypedContractMethod<
    [proposalId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executionTime: TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;

  getProposal: TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [DAOGovernanceOptimized.ProposalStructOutput, string] & {
        prop: DAOGovernanceOptimized.ProposalStructOutput;
        details: string;
      }
    ],
    "view"
  >;

  proposalCounter: TypedContractMethod<[], [bigint], "view">;

  proposalDetails: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  proposals: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        votesFor: bigint;
        votesAgainst: bigint;
        deadline: bigint;
        proposalId: bigint;
        proposalType: bigint;
        category: bigint;
        executed: boolean;
        passed: boolean;
      }
    ],
    "view"
  >;

  propose: TypedContractMethod<
    [
      _type: BigNumberish,
      _category: BigNumberish,
      _description: string,
      _ipfsHash: string
    ],
    [bigint],
    "nonpayable"
  >;

  token: TypedContractMethod<[], [string], "view">;

  voteQuadratic: TypedContractMethod<
    [proposalId: BigNumberish, voteAmount: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;

  votes: TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "QUORUM"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "TIMELOCK"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "VOTING_PERIOD"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "execute"
  ): TypedContractMethod<[proposalId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executionTime"
  ): TypedContractMethod<[arg0: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getProposal"
  ): TypedContractMethod<
    [proposalId: BigNumberish],
    [
      [DAOGovernanceOptimized.ProposalStructOutput, string] & {
        prop: DAOGovernanceOptimized.ProposalStructOutput;
        details: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "proposalCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "proposalDetails"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "proposals"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, bigint, bigint, bigint, bigint, boolean, boolean] & {
        votesFor: bigint;
        votesAgainst: bigint;
        deadline: bigint;
        proposalId: bigint;
        proposalType: bigint;
        category: bigint;
        executed: boolean;
        passed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "propose"
  ): TypedContractMethod<
    [
      _type: BigNumberish,
      _category: BigNumberish,
      _description: string,
      _ipfsHash: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "voteQuadratic"
  ): TypedContractMethod<
    [proposalId: BigNumberish, voteAmount: BigNumberish, support: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "votes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: AddressLike],
    [bigint],
    "view"
  >;

  getEvent(
    key: "ProposalCreated"
  ): TypedContractEvent<
    ProposalCreatedEvent.InputTuple,
    ProposalCreatedEvent.OutputTuple,
    ProposalCreatedEvent.OutputObject
  >;
  getEvent(
    key: "ProposalExecuted"
  ): TypedContractEvent<
    ProposalExecutedEvent.InputTuple,
    ProposalExecutedEvent.OutputTuple,
    ProposalExecutedEvent.OutputObject
  >;
  getEvent(
    key: "VotedQuadratic"
  ): TypedContractEvent<
    VotedQuadraticEvent.InputTuple,
    VotedQuadraticEvent.OutputTuple,
    VotedQuadraticEvent.OutputObject
  >;

  filters: {
    "ProposalCreated(uint32,uint8,uint8)": TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;
    ProposalCreated: TypedContractEvent<
      ProposalCreatedEvent.InputTuple,
      ProposalCreatedEvent.OutputTuple,
      ProposalCreatedEvent.OutputObject
    >;

    "ProposalExecuted(uint32,bool)": TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;
    ProposalExecuted: TypedContractEvent<
      ProposalExecutedEvent.InputTuple,
      ProposalExecutedEvent.OutputTuple,
      ProposalExecutedEvent.OutputObject
    >;

    "VotedQuadratic(uint32,address,uint128,uint256)": TypedContractEvent<
      VotedQuadraticEvent.InputTuple,
      VotedQuadraticEvent.OutputTuple,
      VotedQuadraticEvent.OutputObject
    >;
    VotedQuadratic: TypedContractEvent<
      VotedQuadraticEvent.InputTuple,
      VotedQuadraticEvent.OutputTuple,
      VotedQuadraticEvent.OutputObject
    >;
  };
}
