/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DebateLedgerOptimized {
  export type DebateRecordStruct = {
    id: BigNumberish;
    timestamp: BigNumberish;
    isFinalized: boolean;
  };

  export type DebateRecordStructOutput = [
    id: bigint,
    timestamp: bigint,
    isFinalized: boolean
  ] & { id: bigint; timestamp: bigint; isFinalized: boolean };
}

export interface DebateLedgerOptimizedInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "debateExists"
      | "debates"
      | "finalizeDebate"
      | "getDebate"
      | "nextId"
      | "owner"
      | "recordDebate"
      | "recordStatementBatch"
      | "renounceOwnership"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DebateCreated"
      | "DebateFinalized"
      | "OwnershipTransferred"
      | "StatementBatch"
      | "StatementRecorded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "debateExists",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "debates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "finalizeDebate",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "getDebate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "nextId", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordDebate",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "recordStatementBatch",
    values: [BigNumberish, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "debateExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "debates", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "finalizeDebate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getDebate", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "nextId", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordDebate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordStatementBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DebateCreatedEvent {
  export type InputTuple = [
    id: BigNumberish,
    topic: string,
    ipfsCid: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    topic: string,
    ipfsCid: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    id: bigint;
    topic: string;
    ipfsCid: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebateFinalizedEvent {
  export type InputTuple = [id: BigNumberish, finalIpfsCid: string];
  export type OutputTuple = [id: bigint, finalIpfsCid: string];
  export interface OutputObject {
    id: bigint;
    finalIpfsCid: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatementBatchEvent {
  export type InputTuple = [
    debateId: BigNumberish,
    ipfsHashes: string[],
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    debateId: bigint,
    ipfsHashes: string[],
    timestamp: bigint
  ];
  export interface OutputObject {
    debateId: bigint;
    ipfsHashes: string[];
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatementRecordedEvent {
  export type InputTuple = [
    debateId: BigNumberish,
    agent: AddressLike,
    ipfsHash: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    debateId: bigint,
    agent: string,
    ipfsHash: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    debateId: bigint;
    agent: string;
    ipfsHash: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DebateLedgerOptimized extends BaseContract {
  connect(runner?: ContractRunner | null): DebateLedgerOptimized;
  waitForDeployment(): Promise<this>;

  interface: DebateLedgerOptimizedInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  debateExists: TypedContractMethod<[_id: BigNumberish], [boolean], "view">;

  debates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        id: bigint;
        timestamp: bigint;
        isFinalized: boolean;
      }
    ],
    "view"
  >;

  finalizeDebate: TypedContractMethod<
    [_id: BigNumberish, _finalIpfsCid: string],
    [void],
    "nonpayable"
  >;

  getDebate: TypedContractMethod<
    [_id: BigNumberish],
    [DebateLedgerOptimized.DebateRecordStructOutput],
    "view"
  >;

  nextId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  recordDebate: TypedContractMethod<
    [_topic: string, _ipfsCid: string],
    [void],
    "nonpayable"
  >;

  recordStatementBatch: TypedContractMethod<
    [_debateId: BigNumberish, _ipfsHashes: string[]],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "debateExists"
  ): TypedContractMethod<[_id: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "debates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        id: bigint;
        timestamp: bigint;
        isFinalized: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "finalizeDebate"
  ): TypedContractMethod<
    [_id: BigNumberish, _finalIpfsCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getDebate"
  ): TypedContractMethod<
    [_id: BigNumberish],
    [DebateLedgerOptimized.DebateRecordStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordDebate"
  ): TypedContractMethod<
    [_topic: string, _ipfsCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordStatementBatch"
  ): TypedContractMethod<
    [_debateId: BigNumberish, _ipfsHashes: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DebateCreated"
  ): TypedContractEvent<
    DebateCreatedEvent.InputTuple,
    DebateCreatedEvent.OutputTuple,
    DebateCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DebateFinalized"
  ): TypedContractEvent<
    DebateFinalizedEvent.InputTuple,
    DebateFinalizedEvent.OutputTuple,
    DebateFinalizedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "StatementBatch"
  ): TypedContractEvent<
    StatementBatchEvent.InputTuple,
    StatementBatchEvent.OutputTuple,
    StatementBatchEvent.OutputObject
  >;
  getEvent(
    key: "StatementRecorded"
  ): TypedContractEvent<
    StatementRecordedEvent.InputTuple,
    StatementRecordedEvent.OutputTuple,
    StatementRecordedEvent.OutputObject
  >;

  filters: {
    "DebateCreated(uint64,string,string,uint64)": TypedContractEvent<
      DebateCreatedEvent.InputTuple,
      DebateCreatedEvent.OutputTuple,
      DebateCreatedEvent.OutputObject
    >;
    DebateCreated: TypedContractEvent<
      DebateCreatedEvent.InputTuple,
      DebateCreatedEvent.OutputTuple,
      DebateCreatedEvent.OutputObject
    >;

    "DebateFinalized(uint64,string)": TypedContractEvent<
      DebateFinalizedEvent.InputTuple,
      DebateFinalizedEvent.OutputTuple,
      DebateFinalizedEvent.OutputObject
    >;
    DebateFinalized: TypedContractEvent<
      DebateFinalizedEvent.InputTuple,
      DebateFinalizedEvent.OutputTuple,
      DebateFinalizedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "StatementBatch(uint64,string[],uint64)": TypedContractEvent<
      StatementBatchEvent.InputTuple,
      StatementBatchEvent.OutputTuple,
      StatementBatchEvent.OutputObject
    >;
    StatementBatch: TypedContractEvent<
      StatementBatchEvent.InputTuple,
      StatementBatchEvent.OutputTuple,
      StatementBatchEvent.OutputObject
    >;

    "StatementRecorded(uint64,address,string,uint64)": TypedContractEvent<
      StatementRecordedEvent.InputTuple,
      StatementRecordedEvent.OutputTuple,
      StatementRecordedEvent.OutputObject
    >;
    StatementRecorded: TypedContractEvent<
      StatementRecordedEvent.InputTuple,
      StatementRecordedEvent.OutputTuple,
      StatementRecordedEvent.OutputObject
    >;
  };
}
