/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace DebateSession {
  export type DebateStruct = {
    debateId: BigNumberish;
    topic: string;
    ipfsTranscriptHash: string;
    currentPhase: BigNumberish;
    activeAgents: string[];
    startTime: BigNumberish;
    endTime: BigNumberish;
    consensusReached: boolean;
    consensusPercentage: BigNumberish;
    finalPolicyIpfsHash: string;
    initiator: AddressLike;
  };

  export type DebateStructOutput = [
    debateId: bigint,
    topic: string,
    ipfsTranscriptHash: string,
    currentPhase: bigint,
    activeAgents: string[],
    startTime: bigint,
    endTime: bigint,
    consensusReached: boolean,
    consensusPercentage: bigint,
    finalPolicyIpfsHash: string,
    initiator: string
  ] & {
    debateId: bigint;
    topic: string;
    ipfsTranscriptHash: string;
    currentPhase: bigint;
    activeAgents: string[];
    startTime: bigint;
    endTime: bigint;
    consensusReached: boolean;
    consensusPercentage: bigint;
    finalPolicyIpfsHash: string;
    initiator: string;
  };

  export type StatementStruct = {
    agentId: string;
    statementHash: string;
    timestamp: BigNumberish;
    ipfsContentHash: string;
    agentSignature: BytesLike;
  };

  export type StatementStructOutput = [
    agentId: string,
    statementHash: string,
    timestamp: bigint,
    ipfsContentHash: string,
    agentSignature: string
  ] & {
    agentId: string;
    statementHash: string;
    timestamp: bigint;
    ipfsContentHash: string;
    agentSignature: string;
  };
}

export interface DebateSessionInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "advancePhase"
      | "completeDebate"
      | "debateCounter"
      | "debateStatements"
      | "debateVotes"
      | "debates"
      | "getDebate"
      | "getDebateStatements"
      | "owner"
      | "recordStatement"
      | "recordVote"
      | "renounceOwnership"
      | "startDebate"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DebateCompleted"
      | "DebateStarted"
      | "OwnershipTransferred"
      | "PhaseAdvanced"
      | "StatementRecorded"
      | "VoteCast"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "advancePhase",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "completeDebate",
    values: [BigNumberish, string, string, boolean, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "debateCounter",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "debateStatements",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "debateVotes",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "debates",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDebate",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDebateStatements",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recordStatement",
    values: [BigNumberish, string, string, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "recordVote",
    values: [BigNumberish, string, boolean, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "startDebate",
    values: [string, string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "advancePhase",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "completeDebate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debateCounter",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debateStatements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "debateVotes",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "debates", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getDebate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getDebateStatements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recordStatement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "recordVote", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "startDebate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace DebateCompletedEvent {
  export type InputTuple = [
    debateId: BigNumberish,
    consensusReached: boolean,
    policyHash: string
  ];
  export type OutputTuple = [
    debateId: bigint,
    consensusReached: boolean,
    policyHash: string
  ];
  export interface OutputObject {
    debateId: bigint;
    consensusReached: boolean;
    policyHash: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DebateStartedEvent {
  export type InputTuple = [
    debateId: BigNumberish,
    topic: string,
    initiator: AddressLike
  ];
  export type OutputTuple = [
    debateId: bigint,
    topic: string,
    initiator: string
  ];
  export interface OutputObject {
    debateId: bigint;
    topic: string;
    initiator: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PhaseAdvancedEvent {
  export type InputTuple = [debateId: BigNumberish, newPhase: BigNumberish];
  export type OutputTuple = [debateId: bigint, newPhase: bigint];
  export interface OutputObject {
    debateId: bigint;
    newPhase: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StatementRecordedEvent {
  export type InputTuple = [
    debateId: BigNumberish,
    agentId: string,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    debateId: bigint,
    agentId: string,
    timestamp: bigint
  ];
  export interface OutputObject {
    debateId: bigint;
    agentId: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VoteCastEvent {
  export type InputTuple = [
    debateId: BigNumberish,
    agentId: string,
    support: boolean
  ];
  export type OutputTuple = [
    debateId: bigint,
    agentId: string,
    support: boolean
  ];
  export interface OutputObject {
    debateId: bigint;
    agentId: string;
    support: boolean;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DebateSession extends BaseContract {
  connect(runner?: ContractRunner | null): DebateSession;
  waitForDeployment(): Promise<this>;

  interface: DebateSessionInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  advancePhase: TypedContractMethod<
    [debateId: BigNumberish],
    [void],
    "nonpayable"
  >;

  completeDebate: TypedContractMethod<
    [
      debateId: BigNumberish,
      ipfsTranscriptHash: string,
      finalPolicyIpfsHash: string,
      consensusReached: boolean,
      consensusPercentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  debateCounter: TypedContractMethod<[], [bigint], "view">;

  debateStatements: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint, string, string] & {
        agentId: string;
        statementHash: string;
        timestamp: bigint;
        ipfsContentHash: string;
        agentSignature: string;
      }
    ],
    "view"
  >;

  debateVotes: TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, boolean, bigint, string] & {
        agentId: string;
        support: boolean;
        confidence: bigint;
        reasoning: string;
      }
    ],
    "view"
  >;

  debates: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string,
        string
      ] & {
        debateId: bigint;
        topic: string;
        ipfsTranscriptHash: string;
        currentPhase: bigint;
        startTime: bigint;
        endTime: bigint;
        consensusReached: boolean;
        consensusPercentage: bigint;
        finalPolicyIpfsHash: string;
        initiator: string;
      }
    ],
    "view"
  >;

  getDebate: TypedContractMethod<
    [debateId: BigNumberish],
    [DebateSession.DebateStructOutput],
    "view"
  >;

  getDebateStatements: TypedContractMethod<
    [debateId: BigNumberish],
    [DebateSession.StatementStructOutput[]],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  recordStatement: TypedContractMethod<
    [
      debateId: BigNumberish,
      agentId: string,
      statementHash: string,
      ipfsContentHash: string,
      agentSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  recordVote: TypedContractMethod<
    [
      debateId: BigNumberish,
      agentId: string,
      support: boolean,
      confidence: BigNumberish,
      reasoning: string
    ],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  startDebate: TypedContractMethod<
    [topic: string, activeAgents: string[]],
    [bigint],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "advancePhase"
  ): TypedContractMethod<[debateId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "completeDebate"
  ): TypedContractMethod<
    [
      debateId: BigNumberish,
      ipfsTranscriptHash: string,
      finalPolicyIpfsHash: string,
      consensusReached: boolean,
      consensusPercentage: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "debateCounter"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "debateStatements"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, string, bigint, string, string] & {
        agentId: string;
        statementHash: string;
        timestamp: bigint;
        ipfsContentHash: string;
        agentSignature: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "debateVotes"
  ): TypedContractMethod<
    [arg0: BigNumberish, arg1: BigNumberish],
    [
      [string, boolean, bigint, string] & {
        agentId: string;
        support: boolean;
        confidence: bigint;
        reasoning: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "debates"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        string,
        string
      ] & {
        debateId: bigint;
        topic: string;
        ipfsTranscriptHash: string;
        currentPhase: bigint;
        startTime: bigint;
        endTime: bigint;
        consensusReached: boolean;
        consensusPercentage: bigint;
        finalPolicyIpfsHash: string;
        initiator: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDebate"
  ): TypedContractMethod<
    [debateId: BigNumberish],
    [DebateSession.DebateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDebateStatements"
  ): TypedContractMethod<
    [debateId: BigNumberish],
    [DebateSession.StatementStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "recordStatement"
  ): TypedContractMethod<
    [
      debateId: BigNumberish,
      agentId: string,
      statementHash: string,
      ipfsContentHash: string,
      agentSignature: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordVote"
  ): TypedContractMethod<
    [
      debateId: BigNumberish,
      agentId: string,
      support: boolean,
      confidence: BigNumberish,
      reasoning: string
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "startDebate"
  ): TypedContractMethod<
    [topic: string, activeAgents: string[]],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "DebateCompleted"
  ): TypedContractEvent<
    DebateCompletedEvent.InputTuple,
    DebateCompletedEvent.OutputTuple,
    DebateCompletedEvent.OutputObject
  >;
  getEvent(
    key: "DebateStarted"
  ): TypedContractEvent<
    DebateStartedEvent.InputTuple,
    DebateStartedEvent.OutputTuple,
    DebateStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "PhaseAdvanced"
  ): TypedContractEvent<
    PhaseAdvancedEvent.InputTuple,
    PhaseAdvancedEvent.OutputTuple,
    PhaseAdvancedEvent.OutputObject
  >;
  getEvent(
    key: "StatementRecorded"
  ): TypedContractEvent<
    StatementRecordedEvent.InputTuple,
    StatementRecordedEvent.OutputTuple,
    StatementRecordedEvent.OutputObject
  >;
  getEvent(
    key: "VoteCast"
  ): TypedContractEvent<
    VoteCastEvent.InputTuple,
    VoteCastEvent.OutputTuple,
    VoteCastEvent.OutputObject
  >;

  filters: {
    "DebateCompleted(uint256,bool,string)": TypedContractEvent<
      DebateCompletedEvent.InputTuple,
      DebateCompletedEvent.OutputTuple,
      DebateCompletedEvent.OutputObject
    >;
    DebateCompleted: TypedContractEvent<
      DebateCompletedEvent.InputTuple,
      DebateCompletedEvent.OutputTuple,
      DebateCompletedEvent.OutputObject
    >;

    "DebateStarted(uint256,string,address)": TypedContractEvent<
      DebateStartedEvent.InputTuple,
      DebateStartedEvent.OutputTuple,
      DebateStartedEvent.OutputObject
    >;
    DebateStarted: TypedContractEvent<
      DebateStartedEvent.InputTuple,
      DebateStartedEvent.OutputTuple,
      DebateStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "PhaseAdvanced(uint256,uint8)": TypedContractEvent<
      PhaseAdvancedEvent.InputTuple,
      PhaseAdvancedEvent.OutputTuple,
      PhaseAdvancedEvent.OutputObject
    >;
    PhaseAdvanced: TypedContractEvent<
      PhaseAdvancedEvent.InputTuple,
      PhaseAdvancedEvent.OutputTuple,
      PhaseAdvancedEvent.OutputObject
    >;

    "StatementRecorded(uint256,string,uint256)": TypedContractEvent<
      StatementRecordedEvent.InputTuple,
      StatementRecordedEvent.OutputTuple,
      StatementRecordedEvent.OutputObject
    >;
    StatementRecorded: TypedContractEvent<
      StatementRecordedEvent.InputTuple,
      StatementRecordedEvent.OutputTuple,
      StatementRecordedEvent.OutputObject
    >;

    "VoteCast(uint256,string,bool)": TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
    VoteCast: TypedContractEvent<
      VoteCastEvent.InputTuple,
      VoteCastEvent.OutputTuple,
      VoteCastEvent.OutputObject
    >;
  };
}
