/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace ParliamentRegistry {
  export type AgentStruct = {
    agentId: string;
    name: string;
    owner: AddressLike;
    reputationScore: BigNumberish;
    debatesParticipated: BigNumberish;
    positionsChanged: BigNumberish;
    citationsProvided: BigNumberish;
    isActive: boolean;
    ipfsMetadataHash: string;
  };

  export type AgentStructOutput = [
    agentId: string,
    name: string,
    owner: string,
    reputationScore: bigint,
    debatesParticipated: bigint,
    positionsChanged: bigint,
    citationsProvided: bigint,
    isActive: boolean,
    ipfsMetadataHash: string
  ] & {
    agentId: string;
    name: string;
    owner: string;
    reputationScore: bigint;
    debatesParticipated: bigint;
    positionsChanged: bigint;
    citationsProvided: bigint;
    isActive: boolean;
    ipfsMetadataHash: string;
  };
}

export interface ParliamentRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "agents"
      | "authorizedDeployers"
      | "getAgent"
      | "registerAgent"
      | "updateReputation"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "AgentRegistered" | "ReputationUpdated"
  ): EventFragment;

  encodeFunctionData(functionFragment: "agents", values: [string]): string;
  encodeFunctionData(
    functionFragment: "authorizedDeployers",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "getAgent", values: [string]): string;
  encodeFunctionData(
    functionFragment: "registerAgent",
    values: [string, string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "updateReputation",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "agents", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "authorizedDeployers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getAgent", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerAgent",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateReputation",
    data: BytesLike
  ): Result;
}

export namespace AgentRegisteredEvent {
  export type InputTuple = [agentId: string, owner: AddressLike];
  export type OutputTuple = [agentId: string, owner: string];
  export interface OutputObject {
    agentId: string;
    owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReputationUpdatedEvent {
  export type InputTuple = [agentId: string, newScore: BigNumberish];
  export type OutputTuple = [agentId: string, newScore: bigint];
  export interface OutputObject {
    agentId: string;
    newScore: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ParliamentRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ParliamentRegistry;
  waitForDeployment(): Promise<this>;

  interface: ParliamentRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  agents: TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        agentId: string;
        name: string;
        owner: string;
        reputationScore: bigint;
        debatesParticipated: bigint;
        positionsChanged: bigint;
        citationsProvided: bigint;
        isActive: boolean;
        ipfsMetadataHash: string;
      }
    ],
    "view"
  >;

  authorizedDeployers: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getAgent: TypedContractMethod<
    [agentId: string],
    [ParliamentRegistry.AgentStructOutput],
    "view"
  >;

  registerAgent: TypedContractMethod<
    [agentId: string, name: string, ipfsMetadataHash: string],
    [void],
    "nonpayable"
  >;

  updateReputation: TypedContractMethod<
    [agentId: string, newScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "agents"
  ): TypedContractMethod<
    [arg0: string],
    [
      [
        string,
        string,
        string,
        bigint,
        bigint,
        bigint,
        bigint,
        boolean,
        string
      ] & {
        agentId: string;
        name: string;
        owner: string;
        reputationScore: bigint;
        debatesParticipated: bigint;
        positionsChanged: bigint;
        citationsProvided: bigint;
        isActive: boolean;
        ipfsMetadataHash: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "authorizedDeployers"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getAgent"
  ): TypedContractMethod<
    [agentId: string],
    [ParliamentRegistry.AgentStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "registerAgent"
  ): TypedContractMethod<
    [agentId: string, name: string, ipfsMetadataHash: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateReputation"
  ): TypedContractMethod<
    [agentId: string, newScore: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AgentRegistered"
  ): TypedContractEvent<
    AgentRegisteredEvent.InputTuple,
    AgentRegisteredEvent.OutputTuple,
    AgentRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "ReputationUpdated"
  ): TypedContractEvent<
    ReputationUpdatedEvent.InputTuple,
    ReputationUpdatedEvent.OutputTuple,
    ReputationUpdatedEvent.OutputObject
  >;

  filters: {
    "AgentRegistered(string,address)": TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;
    AgentRegistered: TypedContractEvent<
      AgentRegisteredEvent.InputTuple,
      AgentRegisteredEvent.OutputTuple,
      AgentRegisteredEvent.OutputObject
    >;

    "ReputationUpdated(string,uint256)": TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
    ReputationUpdated: TypedContractEvent<
      ReputationUpdatedEvent.InputTuple,
      ReputationUpdatedEvent.OutputTuple,
      ReputationUpdatedEvent.OutputObject
    >;
  };
}
